name: Build Editor Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: Source/GameSDK/
          dest: adminchatcomms-editor-build.pak
      - uses: actions/upload-artifact@v1
        with:
          name: EditorRelease
          path: ${{ github.workspace }}/adminchatcomms-editor-build.pak
