name: Build Workshop Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: Source/
          dest: ${GITHUB_REPOSITORY#*/}-workshop-build.pak
      - uses: actions/upload-artifact@v1
        with:
          name: WorkshopRelease
          path: ${{ github.workspace }}/${GITHUB_REPOSITORY#*/}-workshop-build.pak
      - name: PublishRelease
        uses: fnkr/github-action-ghr@ghr-options
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_TITLE: Latest Release
          GHR_BODY: Latest Workshop Pak file
          GHR_PATH: ${GITHUB_REPOSITORY#*/}-workshop-build.pak
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
