name: Build Workshop Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: Source/
          dest: adminchatcomms-workshop-build.pak
      - uses: actions/upload-artifact@v1
        with:
          name: WorkshopRelease
          path: ${{ github.workspace }}/adminchatcomms-workshop-build.pak
      - name: PublishRelease
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: adminchatcomms-workshop-build.pak
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
